### ISSUE TITLE
MacOS can't use Long Options

### ISSUE THREAD

**Issue by tiinpa** [sackio/eagleeye#1]
Because MacOS can't use Long Options this script can't be run. Easily replicated as `./extract-faces -h` does return the expected output but `./extract-faces --directory \videos --output \faces` returns the following:

```
xargs: illegal option -- a
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
             [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
             [-s size] [utility [argument ...]]
![Screen Shot 2021-01-16 at 11 14 59 PM](https://user-images.githubusercontent.com/13387768/104830887-1a31d200-5851-11eb-8d19-d6cb615655e8.jpg)

```
I believe this would work if standard options were also assigned to the arguments.

**Comment by HanClinto** [comment]
The problem is that OSX uses its own xargs that has several options which are incompatible with GNU xargs.

We could either translate all of the options from one to the other (assuming that counterparts exist), or simply install GNU xargs via Homebrew (package name is `findutils`) and point our command to use `gxargs` instead of `xargs`.

```
brew install findutils
```

**Comment by sackio** [comment]
Thanks for debugging this. My use of xargs was pretty haphazard. I've refactored to use a node.js script to run the extraction script in parallel (with better progress output, etc.). Feel free to give it a try, or to fork with your xarg mods.
